### ISSUE TITLE
Adapter les opengraph et twittercards sur le layout des épisodes

### ISSUE THREAD

**Issue by bobmaerten** [LeRubyNouveau/lerubynouveau.fr#6]
En donnant le lien d'un épisode sur un réseau social, on pourra avoir directement les infos de l'épisode et non pas celui du podcast en général.

**Comment by abelards** [comment]
Oui, et sur les habitués aussi :)
Il "suffit" de rajouter des layouts qui s'incluent les uns les autres ou de regarder le FrontMatter.
